### PR TITLE
Default variables for UCL projects

### PR DESCRIPTION
**Pull request by dpshelio**

### CODE REVIEW

**Review by heatherkellyucl — APPROVED** [review]
These changes are correct. sched_submit_options, sched_flag_interactive, sched_info, sched_hist are not, but guessing you haven't looked at those yet?

**Review by tkoskela — CHANGES_REQUESTED** [review]
We need to set `sched_info`, `sched_interactive`, `sched_flag_interactive` and `sched_del`. I haven't seen `sched_submit_options` used anywhere but it wouldn't hurt either.

**Review by mattagape — APPROVED** [review]
I'm not familiar with what Myriad uses for all these variables, but it looks like you have adjusted the required changes.

**Comment by dpshelio** [comment]
Updated. I think I've covered them all. @mattgillucl you'll probably need the `sched_hist` for the episode 16. Check whether what I added there is actually correct.

**Review by tkoskela — APPROVED** [review]

**Pull request merged**
