### PR TITLE
Update snippets for lesson 12

### PR DESCRIPTION
**Pull request by tkoskela**
* Info snippet uses `nodetypes` instead of `qhost` to give more compressed info about nodes.
* I picked node 001 arbitrarily for explore snippet, I assume there's no reason to pick any particular node.

### CODE REVIEW

**Review by heatherkellyucl — CHANGES_REQUESTED** [review]
Would recommend running nodetypes and qhost (and every example, really) on Myriad and not Kathleen, as that's where the course will be run. Also Myriad has genuinely different nodetypes and not just ones where the RAM is being returned slightly differently.

**Comment by tkoskela** [comment]
Did I run that on Kathleen? Oops, will fix

**Review by mattagape — APPROVED** [review]
Again, I'm not that familiar with Myriad (yet!!) but I can see that the snip you have provided looks more informative.

**Review by dpshelio — APPROVED** [review]

**Comment by dpshelio** [comment]
@heatherkellyucl comment has been addressed. Squashing to remove the branch merging from history.

**Pull request merged**
